title: Damien Scieur
status: Engineer in Applied Mathematics
employer: Phd. Student at INRIA/ENS
highlighter: pygments
google_analytics:
theme: 
scholar:
  style: _bibliography/custom_bibstyle
  repository: pdf
  bibliography_template: bibliography
  group_by: type,year
  group_order: ascending,descending
mainbibfile: _bibliography/papers.bib
gems:
  - jekyll-maps
maps:
  google:
    api_key: AIzaSyBpZjaOxwQ99hsT0FisGimrnDde9lXpV-A
    marker_cluster:
      enabled: false

