title: Damien Scieur
status: Engineer in Applied Mathematics
employer: Research Scientist at Samsung SAIL Montreal
highlighter: rouge
sass:
    load_paths:
        - bower_components/bootstrap-sass/assets/stylesheets
        - bower_components/bootstrap-sass/assets
        - _sass
google_analytics:
theme: 
encoding: utf-8
scholar:
  style: _bibliography/custom_bibstyle
  bibliography_template: bibliography
  sort_by: year
  order: descending
mainbibfile: _bibliography/references.bib
plugins:
  - jekyll-maps
maps:
  google:
    api_key: 
    marker_cluster:
      enabled: false
collections:
  - project_entries
  - talk_entries
  - presentation_other_entries
  - poster_entries
  - talk_metadata
  - presentation_other_metadata
  - poster_metadata
dir_papers: pdf/papers
dir_slides: pdf/slides
dir_posters: pdf/posters
exclude: ['_site', 'node_modules', 'vendor']
